= Changelog
Rizzen Yazston

== iced_af 0.1.2 (2024-01-23)

* Added the `About` window.

* The fake menu bar About button now works.

* In `README.ascidoc` added some useful tips on adding new windows to the project.

== iced_af 0.1.1 (2024-01-22)

* Currently compiles to `iced` commit `545cc90` (latest commit on `master` branch).

* Commented out the dependency `iced_aw` for now, as `menu` is still outstanding.

* Updated `Container`:

** To support new `Border` and `Shadow` types of `iced`,

** Due to the removal of padding methods from `Limit` type.

* Added some information regarding the design.

== iced_af 0.1.0 (2024-01-19)

* Copy the core from another project being developed and cleaned up the source code

* Create localisation database.

== iced_af 0.0.0 (2024-01-18)

* The `iced_af` project's Git repository initialised with basic directory structure:

* README.asciidoc: Basic project description.

* Using `all_in_one.sqlite` for localisation. It will contain a few Italian entries (translation via Google Translation), purely for demonstration purposes
